# 1. Create a 3x3x3 array with random values 

In [ ]:
 import numpy as np
x= np.random.random((3,3))
print("Array:")
print(x)

Array:
[[0.52477296 0.05623654 0.60540597]
 [0.31019055 0.37688209 0.84570336]
 [0.16383089 0.43095503 0.82020492]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
import numpy as np
d=np.diag(1+np.arange(4),k=-1)
print(d)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
import numpy as np
Z=np.zeros((8,8))
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [ ]:
 
import numpy as np
x= np.random.random((4,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.65508221 0.64323343 0.13663789]
 [0.69315475 0.80231825 0.07419496]
 [0.85981003 0.34240383 0.93056001]
 [0.92273987 0.60368041 0.67113505]]
After normalization:
[[0.67831732 0.6644812  0.07291625]
 [0.72277564 0.85024872 0.        ]
 [0.91738339 0.31319455 1.        ]
 [0.99086822 0.61829409 0.69706265]]


# 5.  How to find common values between two arrays?

In [ ]:
 
import numpy as np
array1 = np.array([[0, 10, 20], [40, 60,50]])
print("Array1: ",array1)
array2 = np.array([[80,20,90],[10, 30, 40]])
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [[ 0 10 20]
 [40 60 50]]
Array2:  [[80 20 90]
 [10 30 40]]
Common values between two arrays:
[10 20 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [ ]:
 
import datetime 
today = datetime.date.today()
yesterday = today - datetime.timedelta(days = 1)
tomorrow = today + datetime.timedelta(days = 1) 
print('Yesterday : ',yesterday)
print('Today : ',today)
print('Tomorrow : ',tomorrow)

Yesterday :  2020-07-27
Today :  2020-07-28
Tomorrow :  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [ ]:
 
import numpy as np
x = np.random.randint(0,10,6)
print("First array:")
print(x)
y = np.random.randint(0,10,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[5 5 3 3 0 0]
Second array:
[6 6 4 4 0 9]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [ ]:
 
import numpy as np
x = np.random.randint(0,10,10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[1 9 0 6 4 8 2 6 3 6]
Maximum value replaced by 0:
[1 0 0 6 4 8 2 6 3 6]


# 9. How to print all the values of an array?

In [ ]:
import numpy as np
C=np.array([[1,3,2],[2,6,7],[9,2,5],[2,1,4]])
for row in C:
 for Val in row:
  print('{:3}'.format(Val))

  1
  3
  2
  2
  6
  7
  9
  2
  5
  2
  1
  4


# 10.Subtract the mean of each row of a matrix

In [ ]:
 
import numpy as np
print("Original matrix:\n")
Arr = np.array([[1,4,8],[9,10,2],[4,2,8]])
print(Arr)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = Arr - Arr.mean(axis=1,keepdims=True)
print(Y)

Original matrix:

[[ 1  4  8]
 [ 9 10  2]
 [ 4  2  8]]

Subtract the mean of each row of the said matrix:

[[-3.33333333 -0.33333333  3.66666667]
 [ 2.          3.         -5.        ]
 [-0.66666667 -2.66666667  3.33333333]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [ ]:
import numpy as np
N=np.ones(10)
I=np.random.randint(0,len(N),20)
N+=np.bincount(I,minlength=len(N))
print(N)

[4. 3. 3. 5. 2. 2. 3. 4. 2. 2.]


# 12.How to get the diagonal of a dot product?

In [ ]:
import numpy as np
A = np.array([[1,3,4],[8,7,3]])
B = np.array([[5,3],[2,4],[1,7]])
print("After dot product: ",np.dot(A,B))
print(np.diag(np.dot(A,B)))

After dot product:  [[15 43]
 [57 73]]
[15 73]


# 13.How to find the most frequent value in an array?

In [ ]:
 
import numpy as np
x = np.random.randint(0, 10, 20)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[2 3 8 1 4 3 9 3 2 1 6 2 2 6 7 5 2 2 2 7]
Most frequent value in the above array:
2


# 14.How to get the n largest values of an array

In [ ]:
 
import numpy as np
N = int(input("Enter the length of the array"))
x = np.arange(N)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Enter the length of the array12
Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[11]


# 15.How to create a record array from a regular array?

In [ ]:
 
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array([12,10,9,3])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 12, 12.2)
(2, 10, 15.)
(3, 9, 20.)
